/* 
 * Created by Kareem El Sayed 
 */
@isTest
public class WeeklyComissionSplitterCalculatorTest {
    /* 
     *
    method to create a list of Weekly_Commission_Splitter__c objects
     
    in this test class check that each DML operation was performed successfully.
    Case 1: Do all the commission splitters start on the same date? 
    Date startDate = wcss[0].Billing_Week_Start_Date__c;
    start the test on wcs record where Billing_Week_Start_Date__c == startDate 

   */
   @isTest
   static void makeData(){
       // check if the data is created in the org.
       
   }
    
   @isTest
    static void testData(){
        //test the cases 
    }
}